"""empty message

Revision ID: 100f546c7408
Revises: None
Create Date: 2017-01-15 01:23:02.035030

"""

# revision identifiers, used by Alembic.
revision = '100f546c7408'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipecard',
    sa.Column('recipe_record_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('recipe_image_url', sa.String(length=300), nullable=False),
    sa.Column('recipe_url', sa.String(length=300), nullable=False),
    sa.Column('ingredients', sa.String(length=2000), nullable=True),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('recipe_record_id')
    )
    op.create_table('diets',
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.Column('diet_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('diet_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('intolerances',
    sa.Column('intol_id', sa.Integer(), nullable=False),
    sa.Column('intol_name', sa.String(length=64), nullable=False),
    sa.Column('intol_description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('intol_id')
    )
    op.create_table('cuisine',
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cuisine_id')
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('is_user_profile', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('diet_id', sa.Integer(), nullable=True),
    sa.Column('diet_reason', sa.String(length=120), nullable=True),
    sa.Column('profile_notes', sa.String(length=300), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diets.diet_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('userintolerances',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('intol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intol_id'], ['intolerances.intol_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('avoid',
    sa.Column('avoid_id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('avoid_id')
    )
    op.create_table('friends',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_profile_id', sa.Integer(), nullable=False),
    sa.Column('friendship_verified_by_email', sa.Boolean(), nullable=True),
    sa.Column('friendship_verified_by_facebook', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('parties',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_party', sa.Date(), nullable=True),
    sa.Column('time_of_party', sa.Time(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('recipebox',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_record_id'], ['recipecard.recipe_record_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('partyrecipes',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('recipe_record_id', sa.Integer(), nullable=False),
    sa.Column('works_for', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.ForeignKeyConstraint(['recipe_record_id'], ['recipecard.recipe_record_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('party_guests',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.party_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_guests')
    op.drop_table('partyrecipes')
    op.drop_table('recipebox')
    op.drop_table('parties')
    op.drop_table('friends')
    op.drop_table('avoid')
    op.drop_table('userintolerances')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('cuisine')
    op.drop_table('intolerances')
    op.drop_table('courses')
    op.drop_table('diets')
    op.drop_table('recipecard')
    ### end Alembic commands ###
