"""empty message

Revision ID: 1c695591f995
Revises: 874bb3be140
Create Date: 2017-01-20 23:13:11.837902

"""

# revision identifiers, used by Alembic.
revision = '1c695591f995'
down_revision = '874bb3be140'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('datetime_of_party', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('parties', 'date_of_party')
    op.drop_column('parties', 'time_of_party')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('time_of_party', postgresql.TIME(timezone=True), nullable=True))
    op.add_column('parties', sa.Column('date_of_party', sa.DATE(), nullable=True))
    op.drop_column('parties', 'datetime_of_party')
    ### end Alembic commands ###
