"""empty message

Revision ID: 1e3c04f332a8
Revises: 323d5080fd8c
Create Date: 2017-03-27 21:57:33.479074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3c04f332a8'
down_revision = '323d5080fd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('cuisine_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parties', 'cuisines', ['cuisine_id'], ['cuisine_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.drop_column('parties', 'cuisine_id')
    # ### end Alembic commands ###
