"""empty message

Revision ID: 23072ba9d14f
Revises: 1c695591f995
Create Date: 2017-02-14 05:30:07.921749

"""

# revision identifiers, used by Alembic.
revision = '23072ba9d14f'
down_revision = '1c695591f995'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
