"""empty message

Revision ID: 2354120c11a3
Revises: 47da9b5be3f8
Create Date: 2017-01-20 02:47:24.361467

"""

# revision identifiers, used by Alembic.
revision = '2354120c11a3'
down_revision = '47da9b5be3f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
