"""empty message

Revision ID: 245ea5d2b691
Revises: 3ab71cfe7fbe
Create Date: 2017-06-22 21:36:17.511200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245ea5d2b691'
down_revision = '3ab71cfe7fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksfor')
    op.add_column('partyrecipes', sa.Column('works_for', sa.String(length=2000), nullable=True))
    op.drop_column('partyrecipes', 'party_recipe_notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partyrecipes', sa.Column('party_recipe_notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('partyrecipes', 'works_for')
    op.create_table('worksfor',
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guest_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guest_profile_id'], [u'profiles.profile_id'], name=u'worksfor_guest_profile_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_card_id'], [u'recipecard.recipe_record_id'], name=u'worksfor_recipe_card_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'worksfor_user_id_fkey'),
    sa.PrimaryKeyConstraint('record_id', name=u'worksfor_pkey')
    )
    # ### end Alembic commands ###
