"""empty message

Revision ID: 26506ac4da27
Revises: 5282a445c28e
Create Date: 2017-01-15 01:39:49.127669

"""

# revision identifiers, used by Alembic.
revision = '26506ac4da27'
down_revision = '5282a445c28e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
