"""empty message

Revision ID: 323d5080fd8c
Revises: 451be9e2fd91
Create Date: 2017-03-23 01:42:36.879519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323d5080fd8c'
down_revision = '451be9e2fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('profile_notes', sa.String(length=300), nullable=True))
    op.add_column('parties', sa.Column('profile_notes', sa.String(length=300), nullable=True))
    op.add_column('party_guests', sa.Column('profile_notes', sa.String(length=300), nullable=True))
    op.add_column('partyrecipes', sa.Column('profile_notes', sa.String(length=300), nullable=True))
    op.drop_column('profiles', 'profile_notes')
    op.add_column('recipebox', sa.Column('profile_notes', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipebox', 'profile_notes')
    op.add_column('profiles', sa.Column('profile_notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('partyrecipes', 'profile_notes')
    op.drop_column('party_guests', 'profile_notes')
    op.drop_column('parties', 'profile_notes')
    op.drop_column('friends', 'profile_notes')
    # ### end Alembic commands ###
