"""empty message

Revision ID: 3940c98232c4
Revises: 26506ac4da27
Create Date: 2017-01-15 01:47:33.803173

"""

# revision identifiers, used by Alembic.
revision = '3940c98232c4'
down_revision = '26506ac4da27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
