"""empty message

Revision ID: 3ab71cfe7fbe
Revises: 998e7834c64d
Create Date: 2017-06-21 17:28:35.989358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab71cfe7fbe'
down_revision = '998e7834c64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worksfor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'worksfor', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worksfor', type_='foreignkey')
    op.drop_column('worksfor', 'user_id')
    # ### end Alembic commands ###
