"""empty message

Revision ID: 451be9e2fd91
Revises: 
Create Date: 2017-03-17 04:23:38.312601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451be9e2fd91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('owned_by_user_id', sa.Integer(), nullable=True))
    op.drop_column('profiles', 'owned_by_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('owned_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'owned_by_user_id')
    # ### end Alembic commands ###
