"""empty message

Revision ID: 5072d6f6da9e
Revises: 245ea5d2b691
Create Date: 2017-06-27 19:56:28.002212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5072d6f6da9e'
down_revision = '245ea5d2b691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partyrecipes', sa.Column('recipe_notes', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partyrecipes', 'recipe_notes')
    # ### end Alembic commands ###
