"""empty message

Revision ID: 5282a445c28e
Revises: 395d5c6d6438
Create Date: 2017-01-15 01:34:55.516437

"""

# revision identifiers, used by Alembic.
revision = '5282a445c28e'
down_revision = '395d5c6d6438'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
