"""empty message

Revision ID: 7be3a4657448
Revises: f8940cb725f5
Create Date: 2017-06-19 16:50:44.326951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be3a4657448'
down_revision = 'f8940cb725f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('private_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'private_profile')
    # ### end Alembic commands ###
