"""empty message

Revision ID: 8c7a2714e906
Revises: 5072d6f6da9e
Create Date: 2017-06-27 20:40:09.147183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7a2714e906'
down_revision = '5072d6f6da9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipecard', sa.Column('source_recipe_url', sa.String(length=300), nullable=False))
    op.add_column('recipecard', sa.Column('spoonacular_recipe_url', sa.String(length=300), nullable=False))
    op.drop_column('recipecard', 'recipe_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipecard', sa.Column('recipe_url', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('recipecard', 'spoonacular_recipe_url')
    op.drop_column('recipecard', 'source_recipe_url')
    # ### end Alembic commands ###
