"""empty message

Revision ID: 994a5900f571
Revises: 
Create Date: 2017-03-09 23:48:17.001949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994a5900f571'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
