"""empty message

Revision ID: 998e7834c64d
Revises: 7be3a4657448
Create Date: 2017-06-20 21:24:23.369381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998e7834c64d'
down_revision = '7be3a4657448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'last_updated')
    # ### end Alembic commands ###
