"""empty message

Revision ID: cdd143affbb5
Revises: 8c7a2714e906
Create Date: 2017-07-05 23:18:28.317182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd143affbb5'
down_revision = '8c7a2714e906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('beta_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'beta_approved')
    # ### end Alembic commands ###
