"""empty message

Revision ID: f8940cb725f5
Revises: 
Create Date: 2017-06-19 16:43:54.572548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8940cb725f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'friendship_verified_by_facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friendship_verified_by_facebook', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
