"""empty message

Revision ID: fff972a95341
Revises: cdd143affbb5
Create Date: 2017-07-10 18:19:38.042785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff972a95341'
down_revision = 'cdd143affbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('private_profile_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'private_profile_title')
    # ### end Alembic commands ###
